/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chris' at '8/13/16 2:24 PM' with Gradle 2.14
 *
 * @author chris, @date 8/13/16 2:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
